export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL',
    LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAIL: 'SEARCH_FAIL',
    SEARCH_REFRESH: 'SEARCH_REFRESH',
    FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',
    FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',
    FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',
};
